version: '3'
services:
  mysql:
    build:
      context: .
    ports:
     - "3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=test
     - MYSQL_USER=user
     - MYSQL_PASSWORD=password