version: '3'
services:
  apache-php:
    build:
      context: ./apache-php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
  mysql:
    build:
      context: ./mysql
    ports:
     - "3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=test
     - MYSQL_USER=user
     - MYSQL_PASSWORD=password